---
apiVersion: v1
kind: Secret
metadata:
  name: tailnet-oauth
  namespace: tailway-system
stringData:
  client_id: # oauth client_id
  client_secret: # oauth client_secret
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: tailnet
  annotations:
    tailway.michaelbeaumont.github.io/tags: tag:k8s
spec:
  controllerName: "tailway.michaelbeaumont.github.io/controller"
  parametersRef:
    kind: Secret
    group: ""
    name: tailnet-oauth
    namespace: tailway-system
